### ISSUE TITLE
It links to my profile

### ISSUE THREAD

**Issue by ssbunyk** [tatarintseva/tatarintseva.github.io#1]
:)

**Comment by tatarintseva** [comment]
Thank you. Changed in commit "Link changed. Now refers to my personal profile"

**Comment by byshovets** [comment]
Should be fdb17f3e298a14fc53f0b8d568700e2b49926571, not 'commit "Link changed. Now refers to my personal profile"'

**Comment by tatarintseva** [comment]
OK, will take into account for future commits
